// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4ynYvpfmXJic6ORvyzuQl-maAOCUvO_Q',
    appId: '1:946252754898:web:04df8d8a76869f45e7620b',
    messagingSenderId: '946252754898',
    projectId: 'led-dht-11-96ffd',
    authDomain: 'led-dht-11-96ffd.firebaseapp.com',
    databaseURL: 'https://led-dht-11-96ffd-default-rtdb.firebaseio.com',
    storageBucket: 'led-dht-11-96ffd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsp1th4mZxkhAUbfBpLEM4cppA0ZJ-x2o',
    appId: '1:946252754898:android:5667c72de32f6e34e7620b',
    messagingSenderId: '946252754898',
    projectId: 'led-dht-11-96ffd',
    databaseURL: 'https://led-dht-11-96ffd-default-rtdb.firebaseio.com',
    storageBucket: 'led-dht-11-96ffd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd_P3uIZfSglmkt2rvPyjqsAjV5e-Rv6k',
    appId: '1:946252754898:ios:224ed01780976a0fe7620b',
    messagingSenderId: '946252754898',
    projectId: 'led-dht-11-96ffd',
    databaseURL: 'https://led-dht-11-96ffd-default-rtdb.firebaseio.com',
    storageBucket: 'led-dht-11-96ffd.appspot.com',
    iosBundleId: 'com.forms.regapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd_P3uIZfSglmkt2rvPyjqsAjV5e-Rv6k',
    appId: '1:946252754898:ios:35b89801151ea49de7620b',
    messagingSenderId: '946252754898',
    projectId: 'led-dht-11-96ffd',
    databaseURL: 'https://led-dht-11-96ffd-default-rtdb.firebaseio.com',
    storageBucket: 'led-dht-11-96ffd.appspot.com',
    iosBundleId: 'com.forms.regapp.RunnerTests',
  );
}
